name: Closed issue message

on:
  issues:
    types: [closed]

jobs:
  auto_comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions-ecosystem/action-add-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_number: ${{ github.event.issue.number }}
          body: |
            :wave: This issue has been closed. 
            
            Please note that comments on closed issues are harder for our team to notice. 
            If you need further help, you can:
            - Mention a team member with @username
            - Open a new issue and reference this one (#${{ github.event.issue.number }})
            
            Thank you for your contribution!
